version: "3"
services:
    vccdb:
        image: mongo:4.2
        container_name: vcc_mongodb
        ports:
            - 27017:27017
#        restart: always

    rabbitmq:
        image: rabbitmq:3.7.17-management
        container_name: vcc_rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        env_file:
            - ./.env
