version: "3"
services:
    vccdb:
        image: mongo:4.2
        container_name: vcc_mongodb
        ports:
            - 27017:27017
        restart: always

    rabbitmq:
        build: ./docker/rabbitmq/
        container_name: vcc_rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        restart: always
        env_file:
            - ./.env
